### ISSUE TITLE
Unable to install helm chart on AWS Cloud Platform

### ISSUE THREAD

**Issue by jadhavnitind** [nickytd/kubernetes-logging-helm#15]
Hi,

I am trying to install [https://github.com/nickytd/kubernetes-logging-helm/tree/kubernetes-logging-3.3.2](url) on AWS EKS but getting error like below.

$ helm install ofd logging/kubernetes-logging
Error: INSTALLATION FAILED: chart requires kubeVersion: >= 1.21.0 which is incompatible with Kubernetes v1.21.5-eks-bc4871b

The required version of Kubernetes is greater than 1.21.0 but EKS and other cloud platforms as well shows kubeversion in different format. like below.

$ kubectl version --short
Client Version: v1.22.2
Server Version: **v1.21.5-eks-bc4871b**

I have tried to change kubeVersion value in Charts.yaml but still it is not working. Am I missing anything here? Could you please help me on this.

**Comment by LHozzan** [comment]
Hi @jadhavnitind .

Thank you for your report.

I think, that problem, you are facing, is [here](https://github.com/nickytd/kubernetes-logging-helm/blob/main/chart/Chart.yaml#L2). Just for testing purpose, can you please remove this line in your helm chart copy and let us know?

If this will working for you, we consider change this pattern in helm chart in next release.

**Comment by jadhavnitind** [comment]
Hi @LHozzan

Same change I had done in above example which isn't working. I had replaced kubeVersion  **1.21.0 value to  v1.21.0** because AWS EKS `kubectl version --short` command shows version as **v1.21.5-eks-bc4871b**.

Please suggest on it.

**Comment by nickytd** [comment]
Hi,
Thanks for the bug report. Can you please check the [with-semver-check](https://github.com/nickytd/kubernetes-logging-helm/tree/with-semver-check) branch?

Cheers

**Comment by nickytd** [comment]
Successfully tested on EKS + AWS LoadBalancer Controller + ingress nginx controller + external dns + cert-manager.
