### ISSUE TITLE
fluentd conf

### ISSUE THREAD

**Issue by thrixton** [nickytd/kubernetes-logging-helm#2]
In the `logs-fluentd` ConfigMap, the `01-sources.conf` value has the entry as below
```
<...>
      kafka_configs {
        "bootstrap.servers": "brokers  logs-kafka-0:9092",
        "group.id": "fluentd"
      }
<...>
```  
When I use this, I get an error from fluentd on startup per below
> ERROR -- : rdkafka: [thrd:brokers logs-kafka-0:9092/bootstrap]: brokers logs-kafka-0:9092/bootstrap: Failed to resolve 'brokers logs-kafka-0:9092': Name or service not known (after 0ms in state CONNECT)

When I change the config per below, it works.
```
<...>
      kafka_configs {
        "bootstrap.servers": "logs-kafka-0:9092",
        "group.id": "fluentd"
      }
<...>
```  

Do you know why this would be?  
I can see that it mirrors the config per the fluentd rdkafka_group config so I'm not sure what's happening.

P.S. Thanks for the great work, it's a massive headstart and great solution.

**Comment by nickytd** [comment]
Thank, the proposal is released in chart version 2.4.1
