### ISSUE TITLE
fluentbit conf: journal_host_path hardcoded in configmap

### ISSUE THREAD

**Issue by nachtfisch** [nickytd/kubernetes-logging-helm#3]
Host path is hardcoded here:

https://github.com/nickytd/kubernetes-logging-helm/blob/d85d670f148128fb7e5372e1c4be8643af9406ec/charts/templates/fluentbit/fluentbit-config.yaml#L55

Fix would be to replace it with

       
`
 Path                {{ .Values.fluentbit.journal_host_path }}
`

I added the fix in PR.

**Comment by nickytd** [comment]
Thanks, the chart now uses the journal_host_path in the volume definition of the fluent-bit.
