### ISSUE TITLE
Unable to recognize ""

### ISSUE THREAD

**Issue by dfishburn** [nickytd/kubernetes-logging-helm#6]
Hi, using the `main` branch, and if I just right up use the command provided on the [readme.md](https://github.com/nickytd/kubernetes-logging-helm/blob/main/README.md), we get an error.

```
$ helm install ofd -n logging logging/kubernetes-logging
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CronJob" in version "batch/v1"
```

**Comment by nickytd** [comment]
Indeed the cronjob v1 is available since [Kubernetes API 1.21 ](https://v1-21.docs.kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/)
Hence the minimum cluster version shall be 1.21 to support the CronJob definition. The helm chart version dependency will be updated to reflect the requirement.

**Comment by dfishburn** [comment]
Thanks for the response, I really appreciate it.
I have upgraded my cluster to 1.21.6
Though I still get a failed deployment
```
$ ./setup.sh
++ dirname ./setup.sh
+ sourcedir=.
+ set -eo pipefail
+ [[ '' == \-\h ]]
+ echo 'setting up kubernetes-logging'
setting up kubernetes-logging
+ kubectl create namespace logging --dry-run=client -o yaml
+ kubectl apply -f -
namespace/logging configured
+ '[' -d ./ssl ']'
+ values=single-node-setup.yaml
+ helm upgrade ofd -n logging --create-namespace -f ./single-node-setup.yaml ./../charts --install --wait-for-jobs --timeout=30m
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /mnt/c/Users/I826639/.kube/iotdevk8s--sandboxbsh-a.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /mnt/c/Users/I826639/.kube/iotdevk8s--sandboxbsh-a.yaml
Release "ofd" does not exist. Installing it now.
coalesce.go:199: warning: cannot overwrite table with non table for tls (map[])
coalesce.go:199: warning: cannot overwrite table with non table for tls (map[])
Error: parse error at (kubernetes-logging/templates/opensearch/.os-master-statefulset.yaml.swp:7): unexpected {{end}}
```

**Comment by dfishburn** [comment]
You closed the [Certificate chains](https://github.com/nickytd/kubernetes-logging-helm/issues/7) issue I had open, so I will continue it here, as I am just trying to get the example to run.

I found this post, [how-do-i-add-an-intermediate-ssl-certificate-to-kubernetes-ingress-tls-configura](https://stackoverflow.com/questions/45796058/how-do-i-add-an-intermediate-ssl-certificate-to-kubernetes-ingress-tls-configura)

Which basically says, if you have an intermediate SSL certificate, append it after the public certificate, so I am moving forward with this approach.

Just trying to get your example script to run with my 3rd party certs.

But when I run, this time I get a different error, though as in the debug log you can see it did create the secrets, so I am a bit surprised about the `tls(map[])` being empty, but that is just a guess.

```
++ dirname ./setup.sh
+ sourcedir=.
+ set -eo pipefail
+ [[ '' == \-\h ]]
+ echo 'setting up kubernetes-logging'
setting up kubernetes-logging
+ kubectl create namespace logging --dry-run=client -o yaml
+ kubectl apply -f -
namespace/logging configured
+ '[' -d ./ssl ']'
+ echo 'setting up tls secrtes'
setting up tls secrtes
+ certs=("opensearch-dashboards" "os")
+ for c in ${certs[@]}
+ kubectl create secret tls opensearch-dashboards-tls -n logging --cert=./ssl/wildcard.crt --key=./ssl/wildcard.key --dry-run=client -o yaml
+ kubectl apply -f -
secret/opensearch-dashboards-tls created
+ for c in ${certs[@]}
+ kubectl create secret tls os-tls -n logging --cert=./ssl/wildcard.crt --key=./ssl/wildcard.key --dry-run=client -o yaml
+ kubectl apply -f -
secret/os-tls created
+ values=single-node-setup.yaml
+ helm upgrade ofd -n logging --create-namespace -f ./single-node-setup.yaml ./../charts --install --wait-for-jobs --timeout=30m
Release "ofd" does not exist. Installing it now.
coalesce.go:199: warning: cannot overwrite table with non table for tls (map[])
coalesce.go:199: warning: cannot overwrite table with non table for tls (map[])
Error: parse error at (kubernetes-logging/templates/opensearch/.os-master-statefulset.yaml.swp:7): unexpected {{end}}
```

Any suggestions?

**Comment by dfishburn** [comment]
All working as expected with API Version 1.21.6
