### ISSUE TITLE
Certificate chains

### ISSUE THREAD

**Issue by dfishburn** [nickytd/kubernetes-logging-helm#7]
I am looking into using your charts to deploy, on three platforms.
- AWS
- Azure
- AliCloud

I want to use my own certificates, of which I have 3 files:
- key
- public certificate
- certificate chain (DigiCert)

I was just looking at your [setup.sh](https://github.com/nickytd/kubernetes-logging-helm/blob/main/examples/setup.sh) and I see:
```
if [ -d "$sourcedir/ssl" ]; then
  echo "setting up tls secrtes"
  certs=("opensearch-dashboards" "os")
  for c in ${certs[@]}; do
    kubectl create secret tls "$c-tls" -n logging \
      --cert=$sourcedir/ssl/wildcard.crt \
      --key=$sourcedir/ssl/wildcard.key \
      --dry-run=client -o yaml | kubectl apply -f - 
  done 
fi 
```

How do we incorporate the chain file?

Thank you,
David

**Comment by nickytd** [comment]
The recommended approach is to use a certificate manager like [jetstack](https://github.com/jetstack/cert-manager) to generate the secrets containing the TLS certificates. Once certificate manager is in place the corresponding annotations can be defined on the ingress level to obtain those. The certificate manager will take care for re-generation.

This example here is for illustration purposes only.

**Comment by dfishburn** [comment]
I found this post, [how-do-i-add-an-intermediate-ssl-certificate-to-kubernetes-ingress-tls-configura](https://stackoverflow.com/questions/45796058/how-do-i-add-an-intermediate-ssl-certificate-to-kubernetes-ingress-tls-configura)

Which basically says, if you have an intermediate SSL certificate, append it after the public certificate, so I am moving forward with this approach.

Just trying to get your example script to run with my 3rd party certs.
