### ISSUE TITLE
Fluent Bit - How to customize the configuration

### ISSUE THREAD

**Issue by dfishburn** [nickytd/kubernetes-logging-helm#8]
We need to customize the Fluent Bit Parsers for our distribution to:
- Provide a list of files / directories to scan of our own pods
- Custom parsers to deal with those format of those files
- Extra gear for Fluent Bit like RecordModifiers and such

I see the parsers specified in `charts/templates/fluentbit/fluentbit-config.yaml`

Within that file are all the parsers that I would like to typically append to.
- fluent-bit.confg
- input-kubernetes.confg
- input-systemd.confg
- filter-kubernetes.confg
- filter-parser.confg
- filter-rewrite.confg
- output-opensearch-nginx.confg
- output-opensearch-journals.confg
- output-opensearch-containers.confg
- output-kafka.confg
- parsers.confg

But I do not see any mechanism built into `values.yaml` to be able to append to this section / these different files

Do you have a suggestion about how to go about customizing this?

Thanks,
David

**Comment by nickytd** [comment]
Hi David, 
this a very good requirement. In general any application specific configurations can be supplied by using config maps or secrets and a controller should be able to align and construct the final configurations for the various components. You are correct at the moment there is no such dynamic mechanism. Collaborations or contributions will help to speed up the implementation of the use case.

Thanks
Niki

**Comment by dfishburn** [comment]
After having everything working, this has some challenges to it.

`charts\templates\fluentbit\fluentbit-config.yaml` has a specific setup inside the file:
```
  fluent-bit.conf: |-
    [SERVICE]
        Flush                         35
        Log_Level                     error
        Daemon                        off
        Parsers_File                  parsers.conf
        HTTP_Server                   On
        HTTP_Listen                   0.0.0.0
        HTTP_Port                     2020
        net.connect_timeout_log_error true
        net.connect_timeout           100
        net.keepalive                 on
        net.keepalive_idle_timeout    60
        net.dns.mode                  TCP
        storage.type                  filesystem
        storage.path                  /var/log/flb-storage/
        storage.sync                  normal
        storage.checksum              off
        storage.backlog.mem_limit     50M
        storage.max_chunks_up         1000
        storage.metrics               on

    @INCLUDE input-*.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE filter-parser.conf
```

We can see here, if I were to create a few new files, with special filenames, they could be included with the `@INCLUDE` commands.
I would need someway via values to specify a directory where the helm charts could copy the files to and then somehow include them, or append them to the `fluentbit-config.yaml`.  See below for an idea.

I am not sure what happens with this line
```
        Parsers_File                  parsers.conf
```
As, I had to significantly add to that file to address my own files. 
I don't think that file supports the @INCLUDE syntax.
So again, we would have to possibly append to that file from my file specified from `values.yaml`?

The `fluentbit-config.yaml` does this:
```
    @INCLUDE input-*.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE filter-parser.conf
    #@INCLUDE filter-rewrite.conf
    {{- if .Values.kafka.enabled }}
    @INCLUDE output-kafka.conf
    {{- else }}
    @INCLUDE output-opensearch-*.conf
    {{- end }}
```
So I like `@INCLUDE input-*.conf`, because I could add additional `include-*` files.
We could change a corresponding change to `@INCLUDE filter-*.conf`

But this gets a little messy with this:
```
    {{- if .Values.kafka.enabled }}
    @INCLUDE output-kafka.conf
    {{- else }}
    @INCLUDE output-opensearch-*.conf
    {{- end }}
```
As I would want to do the same, `@INCLUDE output-*.conf`, but there is already conditional logic around it.
And I don't see the ability to use something like an IF statement to wrap an `[OUTPUT]` to make it conditional.

I am not sure what you are currently doing in other areas of the charts.
But in `values.yaml` perhaps we could do something like:
```
fluentbit:
  customIncludes: 
    - input-custom1.conf
    - input-custom2.conf
    - filter-custom1.conf
    - filter-custom2.conf
    - output-custom1.conf
    - output-custom2.conf
  customParser:
    - parser-custom1.conf
```
Then the charts, would append each of the above files to `fluentbit-config.yaml` and the same to the `parsers.conf`.

Rough idea?  Your thoughts?

**Comment by nickytd** [comment]
Hi,
Yes this is a valid use case. Such kind of flexibility can be implemented in many ways .When the helm templating is not sufficient we can think of a controller that can implement the desired flexibility.
Until a solution is found and implemented, I can suggest to experiment and implement the desired configuration of the fluent-bit in a helm chart fork. In case there is a viable solution, a PR is very much appreciated and we can have a discussion.

Thanks
Niki
